### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by BarbaraPal** [BarbaraPal/APPR-2021-22#1]
Živjo,
svoj projekt oddajam v ocenjevanje. Upam, da se bo vse pravilno prevedlo.
Lep pozdrav,
Barbara

**Comment by katarinabrilej** [comment]
Hvala, bomo ocenili.

Lep pozdrav,
Katarina

**Comment by evadezelak** [comment]
Zdravo, 
pri pregledu tvojega projekta sem opazila, da imaš v kodi narejeno razvrščanje v skupine, nisi pa ga vključila in opisala v poročilu, zato zanj ne boš dobila točk. Če želiš, lahko poročilo popraviš. Sporoči prosim, če boš popravljala, ali ostane tako kot je. 

Lep pozdrav,
Eva

**Comment by BarbaraPal** [comment]
Zdravo,
hvala za opozorilo, sem dodala v poročilo.
Lep pozdrav,
Barbara

**Comment by katarinabrilej** [comment]
Sem vpisala oceno v spletno učilnico.

Lep pozdrav,
Katarina

**Comment by BarbaraPal** [comment]
Hvala!
Lep pozdrav,
Barbara
